export default {
    LOAD_SHOPPING_CART: 'LOAD_SHOPPING_CART',
    INCREMENT_QUANTITY: 'CART_INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'CART_DECREMENT_QUANTITY',
    UPDATE_QUANTITY_FIELD: 'CART_UPDATE_QUANTITY_FIELD',
    ADD_ITEM: 'CART_ADD_ITEM',
    REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CLEAR_ALL_ITEMS: 'CART_CLEAR_ALL_ITEMS'
}